language: node_js
node_js:
  - "6"
  - "7"
env:
  - WEBPACK_VERSION=1 EXTRACT_PLUGIN_VERSION=1
  - WEBPACK_VERSION=2 EXTRACT_PLUGIN_VERSION=2
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - stty columns 120
install:
  - yarn --ignore-scripts
  - yarn remove webpack
  - yarn remove extract-text-webpack-plugin
  - yarn add webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_PLUGIN_VERSION --ignore-scripts || true
script:
  - npm test
